// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.43
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestNavigatorPlus
{
    internal sealed partial class Vsix
    {
        public const string Id = "TestNavigatorPlus.cf1a2ef0-f548-44fc-acce-0b38011f00e1";
        public const string Name = "TestNavigatorPlus";
        public const string Description = @"TestNavigatorPlusTestNav";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Schleuniger";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
