// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.43
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestNavigatorPlus
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TestNavigatorPlusString = "6afac6ed-8645-48b8-9943-dbcc9892fc29";
        public static Guid TestNavigatorPlus = new Guid(TestNavigatorPlusString);

        public const string TestNavigatorPlusCmdSetString = "12345678-1234-1234-1234-123456789012";
        public static Guid TestNavigatorPlusCmdSet = new Guid(TestNavigatorPlusCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MyToolbarGroup = 0x1021;
        public const int TestNavigatorCommandId = 0x0100;
        public const int NavigateToFirstBugId = 0x0101;
        public const int NavigateToNextBugId = 0x0102;
        public const int NavigateToPreviousBugId = 0x0103;
        public const int NavigateToLastBugId = 0x0104;
        public const int NavigateToFirstTestId = 0x0105;
        public const int NavigateToNextTestId = 0x0106;
        public const int NavigateToPreviousTestId = 0x0107;
        public const int NavigateToLastTestId = 0x0108;
        public const int NavigateToFirstErrorId = 0x0109;
        public const int NavigateToNextErrorId = 0x010A;
        public const int NavigateToPreviousErrorId = 0x010B;
        public const int NavigateToLastErrorId = 0x010C;
    }
}
